### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Okay here comes a small question: I searched in NEI but I can't find `Foggles` and `Rain-away`. Where are those two items (or something else)?

### CODE REVIEW

**Comment by elifoster** [comment]
Those are coming in 0.29.

**Comment by 3TUSK** [comment]
Thanks for answer as well as [that tutorial](http://ftb.gamepedia.com/Getting_Started_%28Flaxbeard%27s_Steam_Power%29)!

**Comment by elifoster** [comment]
Oh yeah, how was it? Was it successful?

**Comment by 3TUSK** [comment]
I used flintlock blunderbuss to kill ender dragon today.

**Comment by xbony2** [comment]
Noice.

**Pull request merged**
